"""init

Revision ID: 197231663efb
Revises: 
Create Date: 2026-02-23 15:01:06.036762
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '197231663efb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carmake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carmake_name'), 'carmake', ['name'], unique=True)
    op.create_index(op.f('ix_carmake_slug'), 'carmake', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('buyer', 'seller', 'dealer', 'admin', name='userrole'), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_is_banned'), 'user', ['is_banned'], unique=False)
    op.create_index(op.f('ix_user_phone_e164'), 'user', ['phone_e164'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_verified_at'), 'user', ['verified_at'], unique=False)
    op.create_table('carmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['carmake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carmodel_make_id'), 'carmodel', ['make_id'], unique=False)
    op.create_index(op.f('ix_carmodel_name'), 'carmodel', ['name'], unique=False)
    op.create_index(op.f('ix_carmodel_slug'), 'carmodel', ['slug'], unique=False)
    op.create_table('carlisting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'active', 'sold', 'rejected', 'expired', name='carstatus'), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price_sar', sa.Integer(), nullable=False),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('body_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drivetrain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['carmake.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['carmodel.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carlisting_body_type'), 'carlisting', ['body_type'], unique=False)
    op.create_index(op.f('ix_carlisting_city'), 'carlisting', ['city'], unique=False)
    op.create_index(op.f('ix_carlisting_color'), 'carlisting', ['color'], unique=False)
    op.create_index(op.f('ix_carlisting_condition'), 'carlisting', ['condition'], unique=False)
    op.create_index(op.f('ix_carlisting_created_at'), 'carlisting', ['created_at'], unique=False)
    op.create_index(op.f('ix_carlisting_district'), 'carlisting', ['district'], unique=False)
    op.create_index(op.f('ix_carlisting_drivetrain'), 'carlisting', ['drivetrain'], unique=False)
    op.create_index(op.f('ix_carlisting_fuel_type'), 'carlisting', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_carlisting_make_id'), 'carlisting', ['make_id'], unique=False)
    op.create_index(op.f('ix_carlisting_mileage_km'), 'carlisting', ['mileage_km'], unique=False)
    op.create_index(op.f('ix_carlisting_model_id'), 'carlisting', ['model_id'], unique=False)
    op.create_index(op.f('ix_carlisting_owner_id'), 'carlisting', ['owner_id'], unique=False)
    op.create_index(op.f('ix_carlisting_price_sar'), 'carlisting', ['price_sar'], unique=False)
    op.create_index(op.f('ix_carlisting_published_at'), 'carlisting', ['published_at'], unique=False)
    op.create_index(op.f('ix_carlisting_status'), 'carlisting', ['status'], unique=False)
    op.create_index(op.f('ix_carlisting_transmission'), 'carlisting', ['transmission'], unique=False)
    op.create_index(op.f('ix_carlisting_updated_at'), 'carlisting', ['updated_at'], unique=False)
    op.create_index(op.f('ix_carlisting_year'), 'carlisting', ['year'], unique=False)
    op.create_table('carmedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cdn_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['carlisting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carmedia_car_id'), 'carmedia', ['car_id'], unique=False)
    op.create_index(op.f('ix_carmedia_created_at'), 'carmedia', ['created_at'], unique=False)
    op.create_index(op.f('ix_carmedia_is_cover'), 'carmedia', ['is_cover'], unique=False)
    op.create_index(op.f('ix_carmedia_sort_order'), 'carmedia', ['sort_order'], unique=False)
    op.create_index(op.f('ix_carmedia_storage_key'), 'carmedia', ['storage_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carmedia_storage_key'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_sort_order'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_is_cover'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_created_at'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_car_id'), table_name='carmedia')
    op.drop_table('carmedia')
    op.drop_index(op.f('ix_carlisting_year'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_updated_at'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_transmission'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_status'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_published_at'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_price_sar'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_owner_id'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_model_id'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_mileage_km'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_make_id'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_fuel_type'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_drivetrain'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_district'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_created_at'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_condition'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_color'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_city'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_body_type'), table_name='carlisting')
    op.drop_table('carlisting')
    op.drop_index(op.f('ix_carmodel_slug'), table_name='carmodel')
    op.drop_index(op.f('ix_carmodel_name'), table_name='carmodel')
    op.drop_index(op.f('ix_carmodel_make_id'), table_name='carmodel')
    op.drop_table('carmodel')
    op.drop_index(op.f('ix_user_verified_at'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_phone_e164'), table_name='user')
    op.drop_index(op.f('ix_user_is_banned'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_carmake_slug'), table_name='carmake')
    op.drop_index(op.f('ix_carmake_name'), table_name='carmake')
    op.drop_table('carmake')
    # ### end Alembic commands ###
