"""...

Revision ID: 914b5d25eb4e
Revises: 89fee21b2f2e
Create Date: 2026-02-28 15:17:32.125075
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '914b5d25eb4e'
down_revision: Union[str, Sequence[str], None] = '89fee21b2f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carmake_name'), table_name='carmake')
    op.drop_index(op.f('ix_carmake_slug'), table_name='carmake')
    op.drop_table('carmake')
    op.drop_index(op.f('ix_carmedia_car_id'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_created_at'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_is_cover'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_sort_order'), table_name='carmedia')
    op.drop_index(op.f('ix_carmedia_storage_key'), table_name='carmedia')
    op.drop_table('carmedia')
    op.drop_index(op.f('ix_carmodel_make_id'), table_name='carmodel')
    op.drop_index(op.f('ix_carmodel_name'), table_name='carmodel')
    op.drop_index(op.f('ix_carmodel_slug'), table_name='carmodel')
    op.drop_table('carmodel')
    op.add_column('carlisting', sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('carlisting', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_carlisting_make_id'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_model_id'), table_name='carlisting')
    op.create_index(op.f('ix_carlisting_make'), 'carlisting', ['make'], unique=False)
    op.create_index(op.f('ix_carlisting_model'), 'carlisting', ['model'], unique=False)
    op.drop_constraint(op.f('carlisting_make_id_fkey'), 'carlisting', type_='foreignkey')
    op.drop_constraint(op.f('carlisting_model_id_fkey'), 'carlisting', type_='foreignkey')
    op.drop_column('carlisting', 'make_id')
    op.drop_column('carlisting', 'model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carlisting', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carlisting', sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('carlisting_model_id_fkey'), 'carlisting', 'carmodel', ['model_id'], ['id'])
    op.create_foreign_key(op.f('carlisting_make_id_fkey'), 'carlisting', 'carmake', ['make_id'], ['id'])
    op.drop_index(op.f('ix_carlisting_model'), table_name='carlisting')
    op.drop_index(op.f('ix_carlisting_make'), table_name='carlisting')
    op.create_index(op.f('ix_carlisting_model_id'), 'carlisting', ['model_id'], unique=False)
    op.create_index(op.f('ix_carlisting_make_id'), 'carlisting', ['make_id'], unique=False)
    op.drop_column('carlisting', 'model')
    op.drop_column('carlisting', 'make')
    op.create_table('carmodel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['carmake.id'], name=op.f('carmodel_make_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carmodel_pkey'))
    )
    op.create_index(op.f('ix_carmodel_slug'), 'carmodel', ['slug'], unique=False)
    op.create_index(op.f('ix_carmodel_name'), 'carmodel', ['name'], unique=False)
    op.create_index(op.f('ix_carmodel_make_id'), 'carmodel', ['make_id'], unique=False)
    op.create_table('carmedia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cdn_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_cover', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['carlisting.id'], name=op.f('carmedia_car_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carmedia_pkey'))
    )
    op.create_index(op.f('ix_carmedia_storage_key'), 'carmedia', ['storage_key'], unique=False)
    op.create_index(op.f('ix_carmedia_sort_order'), 'carmedia', ['sort_order'], unique=False)
    op.create_index(op.f('ix_carmedia_is_cover'), 'carmedia', ['is_cover'], unique=False)
    op.create_index(op.f('ix_carmedia_created_at'), 'carmedia', ['created_at'], unique=False)
    op.create_index(op.f('ix_carmedia_car_id'), 'carmedia', ['car_id'], unique=False)
    op.create_table('carmake',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('carmake_pkey'))
    )
    op.create_index(op.f('ix_carmake_slug'), 'carmake', ['slug'], unique=True)
    op.create_index(op.f('ix_carmake_name'), 'carmake', ['name'], unique=True)
    # ### end Alembic commands ###
